"""Merge every Markdown document under docs/ into one Markdown file.

Run from the project root:
    python scripts/merge_docs.py
"""

from __future__ import annotations

import argparse
from pathlib import Path


def iter_markdown_files(docs_dir: Path, output_path: Path) -> list[Path]:
    """Return Markdown files recursively, ordered by project-relative path."""
    return sorted(
        (
            path
            for path in docs_dir.rglob("*")
            if path.is_file()
            and path.suffix.lower() == ".md"
            and path.resolve() != output_path.resolve()
        ),
        key=lambda item: item.relative_to(docs_dir).as_posix(),
    )


def merge_docs(docs_dir: Path, output_path: Path) -> int:
    if not docs_dir.is_dir():
        raise FileNotFoundError(f"Docs directory does not exist: {docs_dir}")

    files = iter_markdown_files(docs_dir, output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="\n") as destination:
        destination.write("# AgentMemEval rebuild documentation\n\n")
        destination.write(
            "This file is generated by `scripts/merge_docs.py`; edit the source files in `docs/`.\n"
        )
        for path in files:
            relative_path = path.relative_to(docs_dir).as_posix()
            content = path.read_text(encoding="utf-8-sig")
            destination.write(f"\n\n---\n\n## Source: `docs/{relative_path}`\n\n")
            destination.write(content.rstrip())
            destination.write("\n")

    print(f"Merged {len(files)} Markdown files into {output_path}")
    return len(files)


def main() -> None:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--docs-dir",
        type=Path,
        default=project_root / "docs",
        help="Documentation directory (default: <project root>/docs).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=project_root / "docs_merged.md",
        help="Destination path (default: <project root>/docs_merged.md).",
    )
    args = parser.parse_args()
    docs_dir = args.docs_dir if args.docs_dir.is_absolute() else project_root / args.docs_dir
    output_path = args.output if args.output.is_absolute() else project_root / args.output
    merge_docs(docs_dir, output_path)


if __name__ == "__main__":
    main()
